### ISSUE TITLE
4. POST 단건 조회 API

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/myinsta#17]

**Comment by sjw2023** [comment]
[Context]
* 게시물 등록, 수정, 삭제를 진행 하였으니 생성된 포스트들을 조회할수 있다.
[Definition of done]
* 1개의 게시물을  조회할수있는 API 개발을 진행
* 예외, 에러 처리
* 완료시 조회 요청된 게시물의 제목과 이미지 경로를 응답값으로 반환
