### ISSUE TITLE
DB 정규화

### ISSUE THREAD

**Issue by sjw2023** [f-lab-edu/myinsta#3]
[설명]
DB 정규화에 대한 학습

[완료 기준]

- [x] 위키 페이지 생성
- [x] 학습 내용 위키에 정리
- [x] 멘토님 확인

**Comment by sjw2023** [comment]
<img width="645" alt="Screen Shot 2022-10-12 at 11 59 02 PM" src="https://user-images.githubusercontent.com/16884433/195377851-85ca8b40-d303-4375-8d50-bfcdecd60cec.png">

**Comment by sjw2023** [comment]
<img width="503" alt="Screen Shot 2022-10-13 at 12 07 50 AM" src="https://user-images.githubusercontent.com/16884433/195379904-9d33c861-834a-48b2-b605-c5d7cc6a5320.png">

**Comment by sjw2023** [comment]
<img width="657" alt="Screen Shot 2022-10-13 at 12 12 00 AM" src="https://user-images.githubusercontent.com/16884433/195380920-bd38a6b3-ba86-4842-8ead-dcb2f5285e4a.png">

**Comment by sjw2023** [comment]
- [x] Timestamp vs datetime 공부
- [x] password 보관시 암호화 공부
- [x] 데이타베이스 데이타 타입 공부

**Comment by sjw2023** [comment]
![Screen Shot 2022-10-16 at 8 57 50 PM](https://user-images.githubusercontent.com/16884433/196034190-ca4b9b02-dcc5-4253-b051-65adca7c6ab1.png)

**Comment by sjw2023** [comment]
- [x] 멘토님 EDR확인

**Comment by f-lab-robert** [comment]
**[ ERD ]**
1. 모든 column 의 자료형에 대해서 표기해주시겠어요 ? ex) bigInt, varchar, timestamp, datetime
2. 모든 column 들이 각각 무엇을 의미하는지 적어주시겠어요 ?
3. post 에 다른 사용자들이 댓글을 달 수 있다고 해보겠습니다. 이 가정을 바탕으로 위의 ERD 를 발전시켜보시겠어요 ?
4. 현재 ERD 상에서 사용자는 0개 또는 1개 이상의 게시글을 갖는다라고 볼 수 있는데요. 의도하신 바가 맞을까요 ?
5. 각각의 관계에 대해서도 설명을 적어주세요.
6. 각 table 의 pk 는 id_table 명으로 적어주세요.
7. imageName 과 imagePath 의 차이는 무엇일까요.
8. camelCase 로 column 명을 가져가도 괜찮을까요 ?

**Comment by f-lab-robert** [comment]
**[ 개인정보의 암호화 ]**
- 단방향, 양방향 암호화에 대해 학습해보시고, 주원님 프로젝트에 어떻게 필요한지 봐보시겠어요 ?

**Comment by f-lab-robert** [comment]
**[MariaDB, MYSQL]**
단순 몇 가지 자료형의 학습을 MariaDB Title 로 Wiki 에 정리하기에는 부족한거 같습니다.

1. DB 엔진 - InnoDB, MyISAM 에 대해 추가 학습
2. MVCC 에 대한 학습

**Comment by sjw2023** [comment]
[설명]
EDR 2차 수정 및 추가 학습
[완료 조건]
- [x] EDR 칼럼에 자료형 추가
- [x] 칼럼의 의미 설명
- [x] 포스트에 댓글 기능추가시 필요한 칼럼 추가
- [x] 각각 관계에 대한 설명
- [x] imageName 또는 imagePath 삭제
- [x] 칼럼이름 케멀케이스에서 언더바 사용으로 바꾸기
- [x] 개인정보 암호화 단방향 양방향 추가 학습
- [x] DB엔진 InnoDB MyISAM 추가 학습
- [x] MVCC 추가 학습

**Comment by sjw2023** [comment]
데이타베이스 네이밍 컨밴션
https://taptorestart.tistory.com/m/entry/MySQL-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EB%AA%85-%ED%85%8C%EC%9D%B4%EB%B8%94%EB%AA%85-%EC%BB%AC%EB%9F%BC%EB%AA%85%EC%9D%80-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%A7%80%EC%96%B4%EC%95%BC-%ED%95%A0%EA%B9%8C

**Comment by sjw2023** [comment]
[각각의 테이블 설명]
![Screen Shot 2022-10-19 at 5 21 38 AM](https://user-images.githubusercontent.com/16884433/196536014-98366b6c-2e7a-4b9c-897a-a7fa2b8c6e98.png)
![Screen Shot 2022-10-19 at 5 21 34 AM](https://user-images.githubusercontent.com/16884433/196536032-10074c44-d62f-4e73-83a9-5124bec6f728.png)
![Screen Shot 2022-10-19 at 5 21 30 AM](https://user-images.githubusercontent.com/16884433/196536046-765e7986-11b0-404d-b969-fa45323e7ae0.png)
![Screen Shot 2022-10-19 at 5 21 22 AM](https://user-images.githubusercontent.com/16884433/196536061-b111cb75-3240-4835-b02d-1184a983ee1e.png)

**Comment by sjw2023** [comment]
[관계 설명]
![Screen Shot 2022-10-19 at 5 21 17 AM](https://user-images.githubusercontent.com/16884433/196536213-f7094acd-b1e5-4c2e-b051-665d918bb872.png)

**Comment by sjw2023** [comment]
[수정 ERD]
![Screen Shot 2022-10-19 at 5 21 14 AM](https://user-images.githubusercontent.com/16884433/196536260-22e6674f-3596-4b3c-b21e-4b4ad2232b22.png)

**Comment by f-lab-robert** [comment]
1. 현재 ERD 구조에서 댓글 작성자의 정보를 어떻게 알 수 있을까요 ?
2. 현재 ERD 구조에서 댓글에 이미지를 첨부할 수 있나요 ? 그렇지 않다면 의도하신 걸까요 ?
3. 현재 ERD 구조에서 댓글에 댓글을 달 수 있나요 ? 그렇지 않다면 의도하신 걸까요 ?

**Comment by sjw2023** [comment]
![Screen Shot 2022-10-21 at 5 50 44 AM](https://user-images.githubusercontent.com/16884433/197055475-6dec77d1-1e42-4177-a165-35fbb1215f93.png)
![Screen Shot 2022-10-21 at 5 50 39 AM](https://user-images.githubusercontent.com/16884433/197055485-02872f87-5235-4f2d-85ed-869364cec4bf.png)

**Comment by f-lab-robert** [comment]
1. comment table 에 보면 id_comment 가 2개가 존재합니다. 즉, 중복입니다. 다시 한번 생각해보시겠어요 ?
2. image table 과 comment table 의 관계를 다시 생각해봐주세요.
3. API 를 만든다고 가정해보시고, 각각의 API 가 호출 될때 설계하신 table 에 데이터가 어떻게 저장이되고 조회가 될지 한번 생각하면서 최종 점검 해주세요.
