### ISSUE TITLE
1. 프로젝트 설정

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/myinsta#5]
**[ Context ]**
- 프로젝트를 진행하기 위해 필요한 초기 설정의 필요성이 생겼다.

**[ Definition of Done ]**
1. github 설정 
- GitHub Pull Request 최소 1 명의 리뷰어를 받아야만 merge 가능하게끔 설정 진행 
- GitHub master branch 로 push 를 막는 설정 진행

2. 라이브러리 설정
- Lombok 설정
- 직접 설치한 DB 와 Spring 의 연결에 대한 설정 진행

3. 기타 이외의 사항

**Comment by sjw2023** [comment]
[github 설정]
* PR 리뷰 설정
* ![Screen Shot 2022-10-30 at 4 14 23 PM](https://user-images.githubusercontent.com/16884433/198866944-41c839ff-9a21-4355-b25c-37b98d8c1a58.png)
* Master브랜치로 푸시 하기 위해서는 다른 브랜치 생성후 하도록 설정
* ![Screen Shot 2022-10-30 at 4 17 00 PM](https://user-images.githubusercontent.com/16884433/198867037-99394ac2-f11b-46dd-a983-1fb80485c309.png)

**Comment by sjw2023** [comment]
[lombok 설정]
* https://projectlombok.org/setup/gradle
* 그래들 설정 파일에 아래 내용 추가 해주기
* ![Screen Shot 2022-10-30 at 4 49 25 PM](https://user-images.githubusercontent.com/16884433/198868061-77d5a62a-0b6b-40c2-ad6c-a31e4b45f840.png)

**Comment by f-lab-robert** [comment]
**[ 추가 학습 사항 ]**
- lombok 및 mybatis 라이브러리 학습 후, 본 issue comment 에 정리

**Comment by sjw2023** [comment]
[Lombok]
[https://docs.google.com/document/d/1S9aTJ3LPf_Lx9nUs-wOJ7pPkCr4_h_jKUBz6vCP0vKQ/edit?usp=sharing](url)

자바에서 BoilerPlates를 annotation 으로 대체 하여 편의성을 제공

@Getter, @Setter, @Builder, @NonNull, @RequiredArgsConstructor, @Value등이 스프링에서 자주 사용된다.

[MyBatis]
[https://docs.google.com/document/d/1wRAAzKnr0aoErRrPWcyX5OyLk-pdM81PSuDokTb7cqg/edit#](url)

JDBC driver와 JDBC API를 통해 수행할 부분을 SqlSession객체로 감싸 Database에 질의를 수행한후 얻어온 데이터 결과를 정의된 ResultMapping방식에 따라 자바 객체에 매핑 시켜주는 프레임워크.

이를 스프링과 사용하기 위해서는
MyBatis-Spring을 통해 SqlSessionFactory및 SqlMapper를 스프링 빈으로 등록 각각을 주입받아 사용.  

혹은 MyBatis-Spring-Boot-Starter를 통해 SqlSession과 Mapper들을 자동으로 빈으로 등록시키는 설정을 Spring-boot-stater-autocaonfiguration에 추가 한 프레임 워크를 사용할수있다.
