### ISSUE TITLE
2. 프로젝트 폴더 구조

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/myinsta#6]
**[ Context ]**
- Spring 에서 사용할 폴더 구조에 대해 조사 후 결정한다.

**[ Definition of Done ]**
- Spring 에서 사용할 폴더 구조에 대해 학습하고, 내가 사용할 폴더 구조에 대해 결정 후에 적절한 근거와 함께 
   본 issue 댓글에 정리한다.

**Comment by sjw2023** [comment]
# 정의
* 소스 파일을 어떤식으로 그룹화 할것인지 정하는 방법.

# 스프링 공홈
* 기본적으로 스프링부트는 application이 구현된 파일을 루트에 나머지 프로젝트의 폴더 구조는 개발자의 자유에 맡기고 있다.
* 하지만 typical structure로 제시한 예시에는 계층구조를 보여주고있다.
* https://docs.spring.io/spring-boot/docs/2.0.8.RELEASE/reference/htmlsingle/#using-boot-structuring-your-code

# 구글링 결과와 다른 사람들의 프로젝트 구조
* 다른 사람들의 프로젝트를 둘러보고 스프링에서 사용하는 폴더 구조를 살펴본 결과 크게 두가지가 있음을 알수있었다.
1. 기능(functionality)들로 그룹화한 구조
* 어플리케이션에서 제공하는 기능별로 Repository, Controller, Service를 모아 좋은 구조
* 각 기능에 관련된 파일이 한번에 모여있어 한 기능에 관련된 구조를 파악하기 쉽다
* 단점으로는 기능들이 퍼져있어, 각 기능간의 연관성파악에 시간이 걸린다.
* 주로 최근 프로젝트들에서 발견되었다.
2. 계층(layer)들로 그룹화한 구조
* Spring MVC의 계층 구조별로 소스파일들을 모아놓은 구조
* Controller는 Controller끼리 Repository는 Repository끼리 모여있다.
* 어플리케이션의 기능이 증가할수록 Controller안의 클래스의 수가 늘어 난다.
* 주로 몇년전에 만들어진 프로젝트에서 발견되었으나, 최신 프로젝트에서도 채택되기도 하였다.

# 무엇을 사용할 것인가 ?
* 최신 프로젝트에서 채택률이 더 높고, 스프링 부트 공식 홈페이지에서도 추천하고 있는 기능 구조를 택하기로 결정하였다.
## 이유
* GitFlow개념에 맞추어 개발을 할것인데, 이는 기능을 추가 할때 해당 기능의 브랜치를 만들고 후에 머지하는 방식이므로 GitFlow와 기능 그룸화방식이 잘 맞는것으로 보인다.
* 계층 그룹화는 클래스 수가 증가할때 복잡해질 서로 관련이 있든 없든 한곳에 모일 클래스 파일들의 구분이 안될것으로 보인다.
* 어플리케이션에서 기능이 추가 되어 문제가발생한다하면 해당 기능의 폴더만 열어 살펴 보면 된다. 

# 참고
* https://studygyaan.com/spring-boot/spring-boot-project-folder-structure-and-best-practices
* https://cheese10yun.github.io/spring-guide-directory/
* https://www.geeksforgeeks.org/spring-boot-code-structure/
* https://docs.spring.io/spring-boot/docs/2.0.8.RELEASE/reference/htmlsingle/#using-boot-structuring-your-code
* https://docs.spring.io/spring-boot/docs/2.0.0.RELEASE/reference/html/using-boot-structuring-your-code.html

**Comment by sjw2023** [comment]
스프링 계층 구조

* Clinent - dto > Controller -> Service -> Repository(dao) - domain > db

모듈(기능)별로 필요한 계층들을 한곳에 모아두는 방법을 사용할 예정
![Screen Shot 2022-11-13 at 3 02 14 PM](https://user-images.githubusercontent.com/16884433/201508469-b874b5bf-a27a-4bce-a738-ee0d7fdd8276.png)

**Comment by sjw2023** [comment]
/controller
/dto
/service
/mapper
/dao

[사용 이유]
Layered Architecture를 따르는 웹 어플리케이션의 기본구조를명확히 보여주는 구조이다.

[각 디렉토리별 하는일 설명]
* 요청을 처리하는 Controller계층
* 처리하기 위한 비즈니스 로직을 제공하는 Service계층
* 비즈니스 로직을 처리하기위해 필요한 정보를 DB에 접근하여 추출하는 DAO계층
* DAO구현에 사용하는 MyBatis mapper를 두기 위한 mapper 디렉토리
* 계층간 정보이동에 사용될 DTO
